### ISSUE TITLE
Exercise Compiler fails with IndexOutOfBounds

### ISSUE THREAD

**Issue by raulraja** [47deg/scala-exercises#182]
```scala
package shapeless
package exercises

/** Shapeless exercises
  * Exercises for shapeless
  */
object ShapelessLib extends exercise.Library {
  override def sections = List(
    HListExercises
  )
}
```
```scala
package shapeless
package exercises

import org.scalatest._

/** HList
  * Hlist is ....
  */
object HListExercises extends FlatSpec with Matchers with exercise.Section {

  /** Some exercise description
    * 
    * {{{
    * Code example.
    * }}}
    *
    */
  def testExercise(res0: Boolean) {
    true should be(res0)
  }

}
```
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.fortysevendeg.exercises.compiler.DocParser$$anonfun$cleanLines$1.apply(DocParser.scala:121)
	at com.fortysevendeg.exercises.compiler.DocParser$$anonfun$cleanLines$1.apply(DocParser.scala:117)
	at scala.collection.immutable.List.map(List.scala:277)
	at com.fortysevendeg.exercises.compiler.DocParser$.cleanLines(DocParser.scala:117)
	at com.fortysevendeg.exercises.compiler.DocParser$.parseExerciseDocComment(DocParser.scala:59)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeExerciseInfo$1$1.apply(Compiler.scala:89)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeExerciseInfo$1$1.apply(Compiler.scala:89)
	at cats.data.Xor.flatMap(Xor.scala:98)
	at cats.data.XorInstances$$anon$1.flatMap(Xor.scala:179)
	at cats.data.XorInstances$$anon$1.flatMap(Xor.scala:175)
	at cats.syntax.FlatMapOps.$greater$greater$eq(flatMap.scala:23)
	at com.fortysevendeg.exercises.compiler.Compiler.com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeExerciseInfo$1(Compiler.scala:89)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeSectionInfo$1$3$$anonfun$apply$10.apply(Compiler.scala:78)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeSectionInfo$1$3$$anonfun$apply$10.apply(Compiler.scala:78)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeSectionInfo$1$3.apply(Compiler.scala:78)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeSectionInfo$1$3.apply(Compiler.scala:70)
	at cats.data.Xor.flatMap(Xor.scala:98)
	at com.fortysevendeg.exercises.compiler.Compiler.com$fortysevendeg$exercises$compiler$Compiler$$maybeMakeSectionInfo$1(Compiler.scala:70)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1$$anonfun$apply$3$$anonfun$apply$4$$anonfun$apply$5.apply(Compiler.scala:59)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1$$anonfun$apply$3$$anonfun$apply$4$$anonfun$apply$5.apply(Compiler.scala:59)
	at cats.data.Xor.flatMap(Xor.scala:98)
	at cats.data.XorInstances$$anon$1.flatMap(Xor.scala:179)
	at cats.data.XorInstances$$anon$1.flatMap(Xor.scala:175)
	at cats.syntax.FlatMapOps.$greater$greater$eq(flatMap.scala:23)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1$$anonfun$apply$3$$anonfun$apply$4.apply(Compiler.scala:59)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1$$anonfun$apply$3$$anonfun$apply$4.apply(Compiler.scala:59)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1$$anonfun$apply$3.apply(Compiler.scala:59)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1$$anonfun$apply$3.apply(Compiler.scala:56)
	at cats.data.Xor.flatMap(Xor.scala:98)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1.apply(Compiler.scala:56)
	at com.fortysevendeg.exercises.compiler.Compiler$$anonfun$maybeMakeLibraryInfo$1$1.apply(Compiler.scala:55)
	at cats.data.Xor.flatMap(Xor.scala:98)
	at com.fortysevendeg.exercises.compiler.Compiler.maybeMakeLibraryInfo$1(Compiler.scala:55)
	at com.fortysevendeg.exercises.compiler.Compiler.compile(Compiler.scala:160)
	at com.fortysevendeg.exercises.compiler.CompilerJava.compile(Compiler.scala:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.fortysevendeg.exercises.sbtexercise.ExerciseCompilerPlugin$$anonfun$generateExercisesTask$1$$anonfun$com$fortysevendeg$exercises$sbtexercise$ExerciseCompilerPlugin$$anonfun$$invokeCompiler$1$1.apply(ExerciseCompilerPlugin.scala:169)
	at com.fortysevendeg.exercises.sbtexercise.ExerciseCompilerPlugin$$anonfun$generateExercisesTask$1$$anonfun$com$fortysevendeg$exercises$sbtexercise$ExerciseCompilerPlugin$$anonfun$$invokeCompiler$1$1.apply(ExerciseCompilerPlugin.scala:164)
	at cats.data.XorFunctions$class.catchNonFatal(Xor.scala:246)
```
This is currently a blocker impeding development of sample of exercises for the stdlib, cats and shapeless and should be of top priority.

**Comment by dialelo** [comment]
I managed to reproduce it adding a trailing space into one of the comment's lines. I pushed a commit with a failing test to the [string-index-out-of-bounds](https://github.com/47deg/scala-exercises/tree/string-index-out-of-bounds) branch.

**Comment by dialelo** [comment]
As a suggestion, maybe for the future, we may want to implement the docstring parsing using parser combinators.

**Comment by andyscott** [comment]
The parsing code is all up for grabs in terms of improvement. I did base the initial parsing on some scala compiler code:

https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/util/DocStrings.scala

**Comment by andyscott** [comment]
@dialelo Awesome job identifying and providing a spec for the failure! This will make a fix easy.
